version: '3.8'

services:
  awx:
    image: ghcr.io/ansible/awx_devel:devel
    container_name: awx_test
    ports:
      - "8080:8080"
    environment:
      SECRET_KEY: awxsecretkey123
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    command: >
      bash -c "
      echo 'Waiting for DB...' &&
      sleep 20 &&
      awx-manage migrate --noinput &&
      echo 'Creating admin user...' &&
      echo \"from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'password')\" | awx-manage shell &&
      supervisord -c /etc/supervisord.conf
      "

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: awx
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass

  redis:
    image: redis:7-alpine
